# Generated by Django 3.1.3 on 2023-01-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230112_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='grade',
        ),
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
